In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [2]:
# import some data to play with
iris = pd.read_csv('iris.csv',index_col=0)

In [3]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [4]:
#Complete Iris dataset
label_encoder = preprocessing.LabelEncoder()
iris['Species']= label_encoder.fit_transform(iris['Species']) 

In [5]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
1           5.1          3.5           1.4          0.2        0
2           4.9          3.0           1.4          0.2        0
3           4.7          3.2           1.3          0.2        0
4           4.6          3.1           1.5          0.2        0
5           5.0          3.6           1.4          0.2        0

In [6]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 6.4 KB


In [7]:
import seaborn as sns
sns.pairplot(iris,hue='Species')

In [8]:
iris['Species'].value_counts().plot.pie()
plt.show()
print(iris['Species'].value_counts())

2    50
1    50
0    50
Name: Species, dtype: int64


In [9]:
x=iris.iloc[:,0:4]
y=iris['Species']

In [10]:
x

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
1             5.1          3.5           1.4          0.2
2             4.9          3.0           1.4          0.2
3             4.7          3.2           1.3          0.2
4             4.6          3.1           1.5          0.2
5             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
146           6.7          3.0           5.2          2.3
147           6.3          2.5           5.0          1.9
148           6.5          3.0           5.2          2.0
149           6.2          3.4           5.4          2.3
150           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [11]:
y

1      0
2      0
3      0
4      0
5      0
      ..
146    2
147    2
148    2
149    2
150    2
Name: Species, Length: 150, dtype: int32

In [12]:
iris['Species'].unique()

array([0, 1, 2])

In [13]:
iris.Species.value_counts()

2    50
1    50
0    50
Name: Species, dtype: int64

In [14]:
colnames = list(iris.columns)
colnames

['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width', 'Species']

In [15]:
# Splitting data into training and testing data set
x_train, x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=40)

### Random Forest

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score,confusion_matrix

In [17]:
num_trees = 400
max_features = 4
kfold = KFold(n_splits=10)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)

In [18]:
model.fit(x_train, y_train)

RandomForestClassifier(max_features=4, n_estimators=400)

In [19]:
accuracy_score(y_test,model.predict(x_test))

1.0

In [20]:
confusion_matrix(y_test,model.predict(x_test))

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 10]], dtype=int64)

In [21]:
preds= model.predict(x_test)

In [22]:
pd.Series(preds).value_counts()

1    12
2    10
0     8
dtype: int64

In [23]:
preds

array([0, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 0, 1, 0, 0, 2, 0, 1])